// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonial
          tag="Über NIVWERK"
          quote="NIVWERK steht für Schweizer Präzision und bedingungslose Liebe zum Detail. Wir behandeln jedes Fahrzeug, als wäre es unser eigenes Meisterwerk."
          author="Markus Weber"
          role="Gründer & Chef-Detailer"
          imageSrc="http://img.b2bpic.net/free-photo/kitchen-drawer-cutlery-organizer-white-cabinet-minimal-style-modern-storage-solution_169016-72197.jpg"
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
