// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Kontakt"
          text="Bereit für das Upgrade Ihres Fahrzeugs? Vereinbaren Sie noch heute einen Termin."
          primaryButton={{
            text: "Jetzt anfragen",
            href: "mailto:info@nivwerk.ch",
          }}
          secondaryButton={{
            text: "Telefon",
            href: "tel:+41440000000",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
