// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Fragen?"
          title="Häufige Fragen"
          description="Alles was Sie über NIVWERK wissen sollten."
          categories={[
            {
              name: "Allgemein",
              items: [
                {
                  question: "Wie lange dauert eine Aufbereitung?",
                  answer: "Je nach Umfang dauert dies zwischen 1 und 3 Tagen.",
                },
                {
                  question: "Wo befinden Sie sich?",
                  answer: "Wir sind zentral in Zürich für Sie tätig.",
                },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
