// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "gallery" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function GallerySection(): React.JSX.Element {
  return (
    <div id="gallery" data-section="gallery">
        <SectionErrorBoundary name="gallery">
              <FeaturesImageBento
          tag="Galerie"
          title="Unsere Arbeiten"
          description="Ein Einblick in die vollendete Ästhetik unserer Fahrzeug-Detailings."
          items={[
            {
              title: "Finish",
              description: "Perfektes Finish",
              imageSrc: "http://img.b2bpic.net/free-photo/superhero-car-vintage-style_23-2151636241.jpg",
            },
            {
              title: "Interieur",
              description: "Details pur",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-empty-room_23-2150528571.jpg",
            },
            {
              title: "Felgen",
              description: "Sauberkeit",
              imageSrc: "http://img.b2bpic.net/free-photo/vinyl-record-with-retro-texture-assortment_23-2149075965.jpg",
            },
            {
              title: "Front",
              description: "Design",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-metallic-car-design_23-2151113103.jpg",
            },
            {
              title: "Logo",
              description: "Markenpräzision",
              imageSrc: "http://img.b2bpic.net/free-photo/headlight-lamp_74190-5517.jpg",
            },
            {
              title: "Studio",
              description: "Arbeitsumfeld",
              imageSrc: "http://img.b2bpic.net/free-photo/breathtaking-view-lightened-tunnel-road_181624-17780.jpg",
            },
            {
              title: "Supercar",
              description: "Resultat",
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-shot-door-handle-modern-red-car_181624-12744.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
