// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBrand from '@/components/sections/hero/HeroBrand';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBrand
          brand="NIVWERK"
          description="mehr als nur sauber"
          primaryButton={{
            text: "TERMIN BUCHEN",
            href: "#contact",
          }}
          secondaryButton={{
            text: "UNSERE LEISTUNGEN",
            href: "#services",
          }}
          imageSrc="https://storage.googleapis.com/webild/users/user_3JmMNFbajJzdaQaLpSwfgd9i6cl/tmp/ultra-realistic-premium-black-sports-car-1790274781749-272a641d.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
