/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import type { LucideIcon } from "lucide-react";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import LoopCarousel from "@/components/ui/LoopCarousel";
import Button from "@/components/ui/Button";
import { useButtonClick } from "@/hooks/useButtonClick";
import { resolveIcon } from "@/utils/resolve-icon";

const items = [
  {
    title: "Innenreinigung",
    description: "Porenfreie Tiefenreinigung, Lederpflege und Veredelung aller Oberflächen für höchste Hygiene.",
    buttonIcon: "ArrowRight",
    buttonHref: "#contact",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3JmMNFbajJzdaQaLpSwfgd9i6cl/tmp/ultra-realistic-premium-car-interior-det-1791227235267-e1f7b891.png"
  },
  {
    title: "Außenreinigung",
    description: "Schonende Handwäsche, Lackkorrektur und Veredelung für makellosen Tiefenglanz.",
    buttonIcon: "ArrowRight",
    buttonHref: "#contact",
    imageSrc: "https://picsum.photos/seed/1172429180/1200/800"
  },
  {
    title: "Komplettreinigung",
    description: "Das ultimative Paket: Perfekt abgestimmte Innen- und Außenaufbereitung auf meisterhaftem Niveau.",
    buttonIcon: "ArrowRight",
    buttonHref: "#contact",
    imageSrc: "https://picsum.photos/seed/441273510/1200/800"
  },
  {
    title: "Felgen & Reifen",
    description: "Intensive Spezialreinigung, Entfernung von Bremsstaub und langanhaltende Versiegelung.",
    buttonIcon: "ArrowRight",
    buttonHref: "#contact",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3JmMNFbajJzdaQaLpSwfgd9i6cl/tmp/ultra-realistic-close-up-of-a-premium-bl-1791227363156-954c3cef.png"
  }
];

type FeatureItem = {
  title: string;
  description: string;
  buttonIcon: string | LucideIcon;
  buttonHref?: string;
  buttonOnClick?: () => void;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesMediaCarouselProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: FeatureItem[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const FeatureMediaCarouselCard = ({ item }: { item: FeatureItem }) => {
  const handleClick = useButtonClick(item.buttonHref, item.buttonOnClick);
  const Icon = resolveIcon(item.buttonIcon);

  return (
    <div className="relative overflow-hidden aspect-square md:aspect-3/2 rounded">
      <ImageOrVideo imageSrc={item.imageSrc} videoSrc={item.videoSrc} className="absolute inset-0" />
      <div className="absolute inset-x-4 bottom-4 xl:inset-x-5 xl:bottom-5 2xl:inset-x-6 2xl:bottom-6 flex items-center justify-between gap-5 p-4 xl:p-5 2xl:p-6 card rounded backdrop-blur-sm">
        <div className="flex flex-col gap-1 min-w-0">
          <h3 className="text-2xl font-semibold leading-snug truncate">{item.title}</h3>
          <p className="text-base leading-snug truncate">{item.description}</p>
        </div>
        <a
          href={item.buttonHref || "#contact"}
          onClick={handleClick}
          aria-label="Mehr erfahren"
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium primary-button rounded-full shrink-0"
        >
          <span>Mehr erfahren</span>
          <Icon className="size-4 text-primary-cta-text" strokeWidth={2} />
        </a>
      </div>
    </div>
  );
};

const ServicesInline = () => {
  return (
    <section aria-label="Features section" className="w-full py-20">
      <div className="flex flex-col w-full gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Expertise"}</p>
          </div>

          <TextAnimation
            text={"Unsere Exklusiv-Leistungen"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Individuelle Lösungen für die Ästhetik und den Erhalt Ihres Fahrzeugs."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
            </div>
          )}
        </div>

        <LoopCarousel>
          {items.map((item) => (
            <FeatureMediaCarouselCard key={item.title} item={item} />
          ))}
        </LoopCarousel>
      </div>
    </section>
  );
};

export default function ServicesSection() {
  return (
    <div data-webild-section="services" data-section="services" id="services">
      <ServicesInline />
    </div>
  );
}
