// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesMediaCarousel from '@/components/sections/features/FeaturesMediaCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesMediaCarousel
          tag="Expertise"
          title="Unsere Exklusiv-Leistungen"
          description="Individuelle Lösungen für die Ästhetik und den Erhalt Ihres Fahrzeugs."
          items={[
            {
              title: "Interieur-Aufbereitung",
              description: "Tiefenreinigung und Veredelung Ihres Fahrzeuginnenraums mit erstklassigen Produkten.",
              buttonIcon: "Sparkles",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-metallic-car_23-2151113206.jpg",
            },
            {
              title: "Exterieur-Veredelung",
              description: "Akribische Aufbereitung des Lacks für ein makelloses, tiefes Finish.",
              buttonIcon: "Sparkles",
              imageSrc: "http://img.b2bpic.net/free-photo/vertical-closeup-shot-green-car-headlamps_181624-8290.jpg",
            },
            {
              title: "Fahrzeug-Schutz",
              description: "Hochwertige Schutzversiegelung für langanhaltenden Glanz und Oberflächenwiderstand.",
              buttonIcon: "Sparkles",
              imageSrc: "http://img.b2bpic.net/free-photo/auto-service-salon-doign-car-wrapping_23-2149593830.jpg",
            },
            {
              title: "Felgen-Aufbereitung",
              description: "Spezielle Reinigung und Pflege für makellose Felgenoptik.",
              buttonIcon: "Sparkles",
              imageSrc: "http://img.b2bpic.net/free-photo/car-wheel-splashing-through-mud_23-2151979276.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
